### ISSUE TITLE
Paginador

### ISSUE THREAD

**Issue by geronm12** [Luchoab/proyectoFinalBackEnd#1]
### Situación actual

Los métodos de los controllers find() no reciben como parámetros las páginas para enviar resultados segmentados y evitar sobrecarga de consulta si son muchos documenbtos a devolver. 

Dejo como ejemplo el método del user.controller.js: 

![image](https://user-images.githubusercontent.com/44532299/232797007-eb2993c6-adcf-4fd4-8d09-3a14421b3756.png)

deberíamos recibir por query string la página y establecer una cantidad de resultados. 

Les dejo un ejemplo sacado de la documentación de MongoDB de cómo realizarlo:

![image](https://user-images.githubusercontent.com/44532299/232797604-61b9f665-9ccd-421d-8192-d0b9a30a4c22.png)

NOTA: No hagan este ajuste en el código de la rama dev o development, con que creen una rama nueva y hagan este ajuste ahí alcanza. Es para evitar romper lo que ya tienen hecho porque paginar el back llevaría  tener que paginar si o si el front.

**Comment by aleli-b** [comment]
Gero como andas, te aclaro que esto no lo hicimos porque en la consigna se marcaba como opcional, de igual manera, ahora mismo me pongo en campaña de hacerlo

**Comment by geronm12** [comment]
Hola Ale, si no te hagas problema. Este issue más que necesario lo coloco para que ustedes puedan ponerlo en práctica, no influye igual en la corrección. Es más como un consejo, pero estaría bueno que lo hagas así tienen el código a mano cuando lo necesiten.

**Comment by aleli-b** [comment]
Joya joya, igual ahi lo termine, ya lo pusheo en la rama pagination

**Comment by aleli-b** [comment]
Hecho!

**Comment by geronm12** [comment]
Buenísmo Ale, ahora los voy revisando y los voy cerrando. Voy a tratar de revisar el front hoy y si está todo ok pasamos a certificación. Si no, les voy a cargar los issues en el repo del front.

**Comment by geronm12** [comment]
Perfecto, checkeado, esta ok.
