### ISSUE TITLE
Crear archivo .env

### ISSUE THREAD

**Issue by geronm12** [Luchoab/proyectoFinalBackEnd#2]
### Situacion

Todos los secretos o api keys o passwords que manejemos en nuestro proyecto deben ser utilizados a partir de un archivo .env. 
Acá dejo ejemplos del código actual:

![image](https://user-images.githubusercontent.com/44532299/232798722-deade860-e77f-4a12-92fa-9a738e9f5b48.png)

![image](https://user-images.githubusercontent.com/44532299/232798773-c6a7d48e-292f-4642-b42e-08301c62524b.png)

### Solución

Crear un archivo .env, instalar el paquete dotenv (npm install dotenv) y en el archivo donde utilizamos express (archivo principal de ejecución de nuestro sistema) debería quedar asi:

**Archivo .env en raíz:** 

![image](https://user-images.githubusercontent.com/44532299/232799226-e2c57795-6e10-4f41-b404-73095d8373f3.png)

**contenido del archivo .env**

![image](https://user-images.githubusercontent.com/44532299/232799326-e76303a5-10d3-4470-a22f-bb724c82ee9d.png)

**archivo inicial del proyecto** 

![image](https://user-images.githubusercontent.com/44532299/232799494-85f88837-eb28-4ee5-8a96-7c0574a825c6.png)

Para poder acceder a los valores en el archivo .env deberemos utilizar process.env y podremos acceder con el siguiente punto a las propiedades de mi archivo .env  ej: process.env.SALT

**Comment by aleli-b** [comment]
Gero como te va, esto esta listo. Si bien se que no corresponde subirlo a github al .env metiendolo en el gitignore, lo subi igual asi lo tengas vos tambien al verlo. Me olvide de decirte que el usuario para admin es admin@role y la contraseña es admin

**Comment by geronm12** [comment]
perfecto Ale, tal cual, no corresponde subirlo a github pero al ser proyecto de final de cursado hacemos la excepción. De todas formas te lo cierro al issue y si querés quitar el .env no hay problema.
