### ISSUE TITLE
Remover comentarios innecesarios

### ISSUE THREAD

**Issue by geronm12** [Luchoab/proyectoFinalBackEnd#3]
### Situación

En los archivos de nuestro proyecto es correcto utilizar comentarios en nuestro código para poder indicar pequeñas cosas sobre su funcionamiento, pero debemos eliminar los comentarios que no sean de utilidad como código que no tiene uso. 

Ejemplo del archivo app.js 

![image](https://user-images.githubusercontent.com/44532299/232800255-e45894d8-d668-4f52-99e9-ef6dd0dbdbc6.png)

### Solución
Sólo debemos remover el comentario

**Comment by aleli-b** [comment]
Listo, ya ha sido eliminado el comentario innecesario

**Comment by geronm12** [comment]
Checkeado, esta ok.
