### ISSUE TITLE
Eliminar los console.logs 

### ISSUE THREAD

**Issue by geronm12** [Luchoab/proyectoFinalBackEnd#4]
### Situación

Es correcto usar console.log en nuestro proyecto mientras estamos desarrollando pero al finalizar y dejar nuestro proyecto funcional debemos eliminar los console.log, les dejo unos ejemplo en los controllers:

![image](https://user-images.githubusercontent.com/44532299/232800783-e17140c9-51db-4465-b035-05d50d797669.png)

![image](https://user-images.githubusercontent.com/44532299/232800820-9f44e9f1-ad88-49bf-b3fc-cf0db455381f.png)

![image](https://user-images.githubusercontent.com/44532299/232800872-768ebeca-6b24-4fa7-9e50-23cfcf41bb49.png)

### Solución
Sólo debemos eliminar los console.log

**Comment by aleli-b** [comment]
Listo gero, se eliminaron todos los console logs, excepto los que informan de la conexión correcta en el index.js

**Comment by geronm12** [comment]
Checkeado, está ok.
